module.exports = {
  tweets: [ { created_at: 'Fri May 11 20:00:17 +0000 2018',
    id: 995030857390968800,
    id_str: '995030857390968834',
    text: 'Cheer on your team on in the #NBAPlayoffs ! All tees marked down!!\n\nLink 👉 https://t.co/Mw77QCXvFr\n\n#Cavs… https://t.co/GdYnoZ5T7v',
    truncated: true,
    entities:
     { hashtags:
        [ { text: 'NBAPlayoffs', indices: [ 29, 41 ] },
          { text: 'Cavs', indices: [ 100, 105 ] } ],
       symbols: [],
       user_mentions: [],
       urls:
        [ { url: 'https://t.co/Mw77QCXvFr',
            expanded_url: 'http://ow.ly/4E1330jXj9M',
            display_url: 'ow.ly/4E1330jXj9M',
            indices: [ 75, 98 ] },
          { url: 'https://t.co/GdYnoZ5T7v',
            expanded_url: 'https://twitter.com/i/web/status/995030857390968834',
            display_url: 'twitter.com/i/web/status/9…',
            indices: [ 107, 130 ] } ] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 905834224053256200,
       id_str: '905834224053256192',
       name: 'The Bench',
       screen_name: 'TheBench_',
       location: 'Indiana, USA',
       description: 'Your source for the latest sports and pop culture news. The home of #BenchPod, #T3C, and @_ClutchPodcast. SHOP: https://t.co/OkTJrU2U9U',
       url: 'https://t.co/DSMcld8QH2',
       entities:
        { url:
           { urls:
              [ { url: 'https://t.co/DSMcld8QH2',
                  expanded_url: 'http://thebenchsports.net',
                  display_url: 'thebenchsports.net',
                  indices: [ 0, 23 ] } ] },
          description:
           { urls:
              [ { url: 'https://t.co/OkTJrU2U9U',
                  expanded_url: 'http://thebenchsports.net/shop',
                  display_url: 'thebenchsports.net/shop',
                  indices: [ 112, 135 ] } ] } },
       protected: false,
       followers_count: 370,
       friends_count: 235,
       listed_count: 1,
       created_at: 'Thu Sep 07 16:44:43 +0000 2017',
       favourites_count: 309,
       utc_offset: -18000,
       time_zone: 'Central Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1523,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/946559563427405830/1IEyXFja_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/946559563427405830/1IEyXFja_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/905834224053256192/1524835839',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Fri May 11 14:00:45 +0000 2018',
    id: 994940377198018600,
    id_str: '994940377198018563',
    text: 'RT @DavidJMays: Blow the @nba up @trailblazers @Bucks @nyknicks @KnicksRMC @warriors #Warriors #Blazers #Bucks #Knicks #NBAPlayoffs #Curry…',
    truncated: false,
    entities:
     { hashtags:
        [ { text: 'Warriors', indices: [ 85, 94 ] },
          { text: 'Blazers', indices: [ 95, 103 ] },
          { text: 'Bucks', indices: [ 104, 110 ] },
          { text: 'Knicks', indices: [ 111, 118 ] },
          { text: 'NBAPlayoffs', indices: [ 119, 131 ] },
          { text: 'Curry', indices: [ 132, 138 ] } ],
       symbols: [],
       user_mentions:
        [ { screen_name: 'DavidJMays',
            name: 'David Mays',
            id: 384108538,
            id_str: '384108538',
            indices: [ 3, 14 ] },
          { screen_name: 'NBA',
            name: 'NBA',
            id: 19923144,
            id_str: '19923144',
            indices: [ 25, 29 ] },
          { screen_name: 'trailblazers',
            name: 'Trail Blazers',
            id: 6395222,
            id_str: '6395222',
            indices: [ 33, 46 ] },
          { screen_name: 'Bucks',
            name: 'Milwaukee Bucks',
            id: 15900167,
            id_str: '15900167',
            indices: [ 47, 53 ] },
          { screen_name: 'nyknicks',
            name: 'NEW YORK KNICKS',
            id: 20265254,
            id_str: '20265254',
            indices: [ 54, 63 ] },
          { screen_name: 'KnicksRMC',
            name: 'NY Knicks RMC (RepMyCity)',
            id: 541133322,
            id_str: '541133322',
            indices: [ 64, 74 ] },
          { screen_name: 'warriors',
            name: 'Golden State Warriors',
            id: 26270913,
            id_str: '26270913',
            indices: [ 75, 84 ] } ],
       urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1720333416,
       id_str: '1720333416',
       name: 'BEAT San Jose',
       screen_name: 'Jhumphreyducks',
       location: 'Cottage Grove, OR',
       description: 'I work for sheldon high school as a camera man, love Oregon ducks especially football, like college football, love all sports, love chewing grizzly wintergreen.',
       url: 'https://t.co/UWajXymZNU',
       entities:
        { url:
           { urls:
              [ { url: 'https://t.co/UWajXymZNU',
                  expanded_url: 'https://www.youtube.com/user/jhumphreyducks',
                  display_url: 'youtube.com/user/jhumphrey…',
                  indices: [ 0, 23 ] } ] },
          description: { urls: [] } },
       protected: false,
       followers_count: 175,
       friends_count: 695,
       listed_count: 2,
       created_at: 'Sun Sep 01 22:09:56 +0000 2013',
       favourites_count: 1202,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 3176,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/980321971085852672/O7Vst0uG_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/980321971085852672/O7Vst0uG_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/1720333416/1522561697',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Fri May 11 05:03:02 +0000 2018',
       id: 994805056087167000,
       id_str: '994805056087166977',
       text: 'Blow the @nba up @trailblazers @Bucks @nyknicks @KnicksRMC @warriors #Warriors #Blazers #Bucks #Knicks #NBAPlayoffs… https://t.co/Z3zKhkSzen',
       truncated: true,
       entities:
        { hashtags:
           [ { text: 'Warriors', indices: [ 69, 78 ] },
             { text: 'Blazers', indices: [ 79, 87 ] },
             { text: 'Bucks', indices: [ 88, 94 ] },
             { text: 'Knicks', indices: [ 95, 102 ] },
             { text: 'NBAPlayoffs', indices: [ 103, 115 ] } ],
          symbols: [],
          user_mentions:
           [ { screen_name: 'NBA',
               name: 'NBA',
               id: 19923144,
               id_str: '19923144',
               indices: [ 9, 13 ] },
             { screen_name: 'trailblazers',
               name: 'Trail Blazers',
               id: 6395222,
               id_str: '6395222',
               indices: [ 17, 30 ] },
             { screen_name: 'Bucks',
               name: 'Milwaukee Bucks',
               id: 15900167,
               id_str: '15900167',
               indices: [ 31, 37 ] },
             { screen_name: 'nyknicks',
               name: 'NEW YORK KNICKS',
               id: 20265254,
               id_str: '20265254',
               indices: [ 38, 47 ] },
             { screen_name: 'KnicksRMC',
               name: 'NY Knicks RMC (RepMyCity)',
               id: 541133322,
               id_str: '541133322',
               indices: [ 48, 58 ] },
             { screen_name: 'warriors',
               name: 'Golden State Warriors',
               id: 26270913,
               id_str: '26270913',
               indices: [ 59, 68 ] } ],
          urls:
           [ { url: 'https://t.co/Z3zKhkSzen',
               expanded_url: 'https://twitter.com/i/web/status/994805056087166977',
               display_url: 'twitter.com/i/web/status/9…',
               indices: [ 117, 140 ] } ] },
       metadata: { iso_language_code: 'en', result_type: 'recent' },
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user:
        { id: 384108538,
          id_str: '384108538',
          name: 'David Mays',
          screen_name: 'DavidJMays',
          location: 'Willamette Valley, OR',
          description: 'Oregon Native! #GoBeavs I try to play golf. Dan Patrick is my idol Buccaneers Padres fanatic Blazers Army Canucks EMT in training 🚑 #LetsGoPadres',
          url: null,
          entities: { description: { urls: [] } },
          protected: false,
          followers_count: 1128,
          friends_count: 826,
          listed_count: 65,
          created_at: 'Mon Oct 03 02:46:50 +0000 2011',
          favourites_count: 47371,
          utc_offset: -25200,
          time_zone: 'Pacific Time (US & Canada)',
          geo_enabled: true,
          verified: false,
          statuses_count: 68896,
          lang: 'en',
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: '4A913C',
          profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/677149127382138882/skRR82dD.jpg',
          profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/677149127382138882/skRR82dD.jpg',
          profile_background_tile: false,
          profile_image_url: 'http://pbs.twimg.com/profile_images/985458885904424960/VR-KyT5N_normal.jpg',
          profile_image_url_https: 'https://pbs.twimg.com/profile_images/985458885904424960/VR-KyT5N_normal.jpg',
          profile_banner_url: 'https://pbs.twimg.com/profile_banners/384108538/1476146555',
          profile_link_color: 'FFAA77',
          profile_sidebar_border_color: 'FFFFFF',
          profile_sidebar_fill_color: 'DDEEF6',
          profile_text_color: '333333',
          profile_use_background_image: true,
          has_extended_profile: true,
          default_profile: false,
          default_profile_image: false,
          following: false,
          follow_request_sent: false,
          notifications: false,
          translator_type: 'none' },
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Fri May 11 13:57:44 +0000 2018',
    id: 994939619098660900,
    id_str: '994939619098660864',
    text: 'RT @Tim_Kitzrow: My NBA JAM take on the Warriors/Pelicans series #curry #nbaplayoffs #KD #Warriors https://t.co/9DDBs3owpp https://t.co/ciU…',
    truncated: false,
    entities:
     { hashtags:
        [ { text: 'curry', indices: [ 65, 71 ] },
          { text: 'nbaplayoffs', indices: [ 72, 84 ] },
          { text: 'KD', indices: [ 85, 88 ] },
          { text: 'Warriors', indices: [ 89, 98 ] } ],
       symbols: [],
       user_mentions:
        [ { screen_name: 'Tim_Kitzrow',
            name: 'Tim Kitzrow',
            id: 305709834,
            id_str: '305709834',
            indices: [ 3, 15 ] } ],
       urls:
        [ { url: 'https://t.co/9DDBs3owpp',
            expanded_url: 'https://www.instagram.com/p/BinTjDigdpO/?taken-by=warriorshttps://www.instagram.com/p/BinTjDigdpO/?taken-by=warriors',
            display_url: 'instagram.com/p/BinTjDigdpO/…',
            indices: [ 99, 122 ] } ] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 3041081613,
       id_str: '3041081613',
       name: 'Insert Coin Doc',
       screen_name: 'insertcoindoc',
       location: '',
       description: 'The amazing behind the scenes documentary about #MortalKombat, #NBAJam and other classic Midway arcade games of the \'90s. Produced by @joshytsui.',
       url: 'https://t.co/ZLbyFpLwAE',
       entities:
        { url:
           { urls:
              [ { url: 'https://t.co/ZLbyFpLwAE',
                  expanded_url: 'http://www.insertcoindoc.com',
                  display_url: 'insertcoindoc.com',
                  indices: [ 0, 23 ] } ] },
          description: { urls: [] } },
       protected: false,
       followers_count: 1502,
       friends_count: 778,
       listed_count: 26,
       created_at: 'Mon Feb 16 17:37:10 +0000 2015',
       favourites_count: 1595,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 2344,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '000000',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/981867784882786304/vLBviOBb_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/981867784882786304/vLBviOBb_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/3041081613/1521037844',
       profile_link_color: 'ABB8C2',
       profile_sidebar_border_color: '000000',
       profile_sidebar_fill_color: '000000',
       profile_text_color: '000000',
       profile_use_background_image: false,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Fri May 11 00:27:25 +0000 2018',
       id: 994735693858558000,
       id_str: '994735693858557952',
       text: 'My NBA JAM take on the Warriors/Pelicans series #curry #nbaplayoffs #KD #Warriors https://t.co/9DDBs3owpp https://t.co/ciUAICM2Rx',
       truncated: false,
       entities:
        { hashtags:
           [ { text: 'curry', indices: [ 48, 54 ] },
             { text: 'nbaplayoffs', indices: [ 55, 67 ] },
             { text: 'KD', indices: [ 68, 71 ] },
             { text: 'Warriors', indices: [ 72, 81 ] } ],
          symbols: [],
          user_mentions: [],
          urls:
           [ { url: 'https://t.co/9DDBs3owpp',
               expanded_url: 'https://www.instagram.com/p/BinTjDigdpO/?taken-by=warriorshttps://www.instagram.com/p/BinTjDigdpO/?taken-by=warriors',
               display_url: 'instagram.com/p/BinTjDigdpO/…',
               indices: [ 82, 105 ] } ],
          media:
           [ { id: 994735082727460900,
               id_str: '994735082727460864',
               indices: [ 106, 129 ],
               media_url: 'http://pbs.twimg.com/media/Dc4CSZOW0AA6Nqq.jpg',
               media_url_https: 'https://pbs.twimg.com/media/Dc4CSZOW0AA6Nqq.jpg',
               url: 'https://t.co/ciUAICM2Rx',
               display_url: 'pic.twitter.com/ciUAICM2Rx',
               expanded_url: 'https://twitter.com/Tim_Kitzrow/status/994735693858557952/photo/1',
               type: 'photo',
               sizes:
                { medium: { w: 795, h: 675, resize: 'fit' },
                  thumb: { w: 150, h: 150, resize: 'crop' },
                  small: { w: 680, h: 577, resize: 'fit' },
                  large: { w: 795, h: 675, resize: 'fit' } } } ] },
       extended_entities:
        { media:
           [ { id: 994735082727460900,
               id_str: '994735082727460864',
               indices: [ 106, 129 ],
               media_url: 'http://pbs.twimg.com/media/Dc4CSZOW0AA6Nqq.jpg',
               media_url_https: 'https://pbs.twimg.com/media/Dc4CSZOW0AA6Nqq.jpg',
               url: 'https://t.co/ciUAICM2Rx',
               display_url: 'pic.twitter.com/ciUAICM2Rx',
               expanded_url: 'https://twitter.com/Tim_Kitzrow/status/994735693858557952/photo/1',
               type: 'photo',
               sizes:
                { medium: { w: 795, h: 675, resize: 'fit' },
                  thumb: { w: 150, h: 150, resize: 'crop' },
                  small: { w: 680, h: 577, resize: 'fit' },
                  large: { w: 795, h: 675, resize: 'fit' } } } ] },
       metadata: { iso_language_code: 'en', result_type: 'recent' },
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user:
        { id: 305709834,
          id_str: '305709834',
          name: 'Tim Kitzrow',
          screen_name: 'Tim_Kitzrow',
          location: 'Chicago, IL',
          description: 'Original voice of NBA JAM, Mutant Football League,NFL BLITZ, MLB SLUGFEST,NHL HITZ,Wayne Gretzky 3D Hockey and over 15 pinball games including The Twilight Zone',
          url: 'https://t.co/dyS45mX4qp',
          entities:
           { url:
              { urls:
                 [ { url: 'https://t.co/dyS45mX4qp',
                     expanded_url: 'http://timkitzrow.com/',
                     display_url: 'timkitzrow.com',
                     indices: [ 0, 23 ] } ] },
             description: { urls: [] } },
          protected: false,
          followers_count: 777,
          friends_count: 582,
          listed_count: 6,
          created_at: 'Thu May 26 17:32:17 +0000 2011',
          favourites_count: 151,
          utc_offset: null,
          time_zone: null,
          geo_enabled: false,
          verified: false,
          statuses_count: 411,
          lang: 'en',
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: 'C0DEED',
          profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
          profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
          profile_background_tile: false,
          profile_image_url: 'http://pbs.twimg.com/profile_images/963903773117763584/dkBEP7vn_normal.jpg',
          profile_image_url_https: 'https://pbs.twimg.com/profile_images/963903773117763584/dkBEP7vn_normal.jpg',
          profile_banner_url: 'https://pbs.twimg.com/profile_banners/305709834/1444925895',
          profile_link_color: '1DA1F2',
          profile_sidebar_border_color: 'C0DEED',
          profile_sidebar_fill_color: 'DDEEF6',
          profile_text_color: '333333',
          profile_use_background_image: true,
          has_extended_profile: false,
          default_profile: true,
          default_profile_image: false,
          following: false,
          follow_request_sent: false,
          notifications: false,
          translator_type: 'none' },
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 3,
       favorite_count: 12,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 3,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Fri May 11 12:35:21 +0000 2018',
    id: 994918883000750100,
    id_str: '994918883000750081',
    text: 'NBA Stars Phone Case For iPhone 7plus 7 6 6S \n@realcasepeace \nhttps://t.co/OP0arevKiM \nBuy Now:… https://t.co/KLNeHkaOLH',
    truncated: true,
    entities:
     { hashtags: [],
       symbols: [],
       user_mentions:
        [ { screen_name: 'realcasepeace',
            name: 'Case Peace',
            id: 872144468044116000,
            id_str: '872144468044115968',
            indices: [ 46, 60 ] } ],
       urls:
        [ { url: 'https://t.co/OP0arevKiM',
            expanded_url: 'http://www.casepeace.com',
            display_url: 'casepeace.com',
            indices: [ 62, 85 ] },
          { url: 'https://t.co/KLNeHkaOLH',
            expanded_url: 'https://twitter.com/i/web/status/994918883000750081',
            display_url: 'twitter.com/i/web/status/9…',
            indices: [ 97, 120 ] } ] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 872144468044116000,
       id_str: '872144468044115968',
       name: 'Case Peace',
       screen_name: 'realcasepeace',
       location: 'United States',
       description: 'Express your individuality with a unique mobile phone case  from Casepeace!\nhttps://t.co/hFuoaXowMQ',
       url: null,
       entities:
        { description:
           { urls:
              [ { url: 'https://t.co/hFuoaXowMQ',
                  expanded_url: 'http://www.casepeace.com',
                  display_url: 'casepeace.com',
                  indices: [ 76, 99 ] } ] } },
       protected: false,
       followers_count: 295,
       friends_count: 123,
       listed_count: 1,
       created_at: 'Tue Jun 06 17:33:39 +0000 2017',
       favourites_count: 4,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 835,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/872146411676106752/72qhJEVJ_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/872146411676106752/72qhJEVJ_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/872144468044115968/1496770966',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Fri May 11 10:24:01 +0000 2018',
    id: 994885831931433000,
    id_str: '994885831931432961',
    text: 'RT @EddieAkaEpo: Get off Bron Bron\'s sack #Kb24 😂\nI nice tho\n\n#Nba #NBACommunityAssist #la #Cavs #Kobe #Lebron #Curry #warriors  #ESPN #bas…',
    truncated: false,
    entities:
     { hashtags:
        [ { text: 'Kb24', indices: [ 42, 47 ] },
          { text: 'Nba', indices: [ 62, 66 ] },
          { text: 'NBACommunityAssist', indices: [ 67, 86 ] },
          { text: 'la', indices: [ 87, 90 ] },
          { text: 'Cavs', indices: [ 91, 96 ] },
          { text: 'Kobe', indices: [ 97, 102 ] },
          { text: 'Lebron', indices: [ 103, 110 ] },
          { text: 'Curry', indices: [ 111, 117 ] },
          { text: 'warriors', indices: [ 118, 127 ] },
          { text: 'ESPN', indices: [ 129, 134 ] } ],
       symbols: [],
       user_mentions:
        [ { screen_name: 'EddieAkaEpo',
            name: '501 E-PO',
            id: 374802902,
            id_str: '374802902',
            indices: [ 3, 15 ] } ],
       urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 292205660,
       id_str: '292205660',
       name: 'D.Lynch',
       screen_name: 'dlynchforeal',
       location: 'San Diego, CA',
       description: 'Emcee/Producer. Credits: Snoop Dogg, Wiz Khalifa, Rick Ross, Royce Da 5\'9, Hopsin,  Famous Dex, A$AP Mob, Future, Lil Wayne, Busta Rhymes, Raekwon',
       url: 'https://t.co/oOU1U1jFg6',
       entities:
        { url:
           { urls:
              [ { url: 'https://t.co/oOU1U1jFg6',
                  expanded_url: 'http://redlabelrecs.com',
                  display_url: 'redlabelrecs.com',
                  indices: [ 0, 23 ] } ] },
          description: { urls: [] } },
       protected: false,
       followers_count: 11765,
       friends_count: 580,
       listed_count: 37,
       created_at: 'Tue May 03 08:29:12 +0000 2011',
       favourites_count: 10207,
       utc_offset: -25200,
       time_zone: 'Arizona',
       geo_enabled: true,
       verified: false,
       statuses_count: 11061,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '000000',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/853043456939245568/x-KRjArk_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/853043456939245568/x-KRjArk_normal.jpg',
       profile_link_color: 'E81C4F',
       profile_sidebar_border_color: '000000',
       profile_sidebar_fill_color: '000000',
       profile_text_color: '000000',
       profile_use_background_image: false,
       has_extended_profile: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Fri May 11 04:19:47 +0000 2018',
       id: 994794170937233400,
       id_str: '994794170937233409',
       text: 'Get off Bron Bron\'s sack #Kb24 😂\nI nice tho\n\n#Nba #NBACommunityAssist #la #Cavs #Kobe #Lebron #Curry #warriors… https://t.co/htns7F3W5a',
       truncated: true,
       entities:
        { hashtags:
           [ { text: 'Kb24', indices: [ 25, 30 ] },
             { text: 'Nba', indices: [ 45, 49 ] },
             { text: 'NBACommunityAssist', indices: [ 50, 69 ] },
             { text: 'la', indices: [ 70, 73 ] },
             { text: 'Cavs', indices: [ 74, 79 ] },
             { text: 'Kobe', indices: [ 80, 85 ] },
             { text: 'Lebron', indices: [ 86, 93 ] },
             { text: 'Curry', indices: [ 94, 100 ] },
             { text: 'warriors', indices: [ 101, 110 ] } ],
          symbols: [],
          user_mentions: [],
          urls:
           [ { url: 'https://t.co/htns7F3W5a',
               expanded_url: 'https://twitter.com/i/web/status/994794170937233409',
               display_url: 'twitter.com/i/web/status/9…',
               indices: [ 112, 135 ] } ] },
       metadata: { iso_language_code: 'en', result_type: 'recent' },
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user:
        { id: 374802902,
          id_str: '374802902',
          name: '501 E-PO',
          screen_name: 'EddieAkaEpo',
          location: 'Arkansas, USA',
          description: '501 💸💸 479,\n2016 College Grad! \nHip Hop Artist/Song Writer/Audio Engineer\nDistributed through @BentleyRecords \nCEO @501FOE\nclick my link for features/services',
          url: 'https://t.co/2ITxCMrVEj',
          entities:
           { url:
              { urls:
                 [ { url: 'https://t.co/2ITxCMrVEj',
                     expanded_url: 'https://www.fiverr.com/eddieakaepo',
                     display_url: 'fiverr.com/eddieakaepo',
                     indices: [ 0, 23 ] } ] },
             description: { urls: [] } },
          protected: false,
          followers_count: 1013,
          friends_count: 859,
          listed_count: 29,
          created_at: 'Sat Sep 17 00:01:49 +0000 2011',
          favourites_count: 978,
          utc_offset: null,
          time_zone: null,
          geo_enabled: true,
          verified: false,
          statuses_count: 2860,
          lang: 'en',
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: 'C0DEED',
          profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/642883021/vsu23xf030iie8v5ppp9.png',
          profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/642883021/vsu23xf030iie8v5ppp9.png',
          profile_background_tile: true,
          profile_image_url: 'http://pbs.twimg.com/profile_images/955964785648132097/VzmQBfVJ_normal.jpg',
          profile_image_url_https: 'https://pbs.twimg.com/profile_images/955964785648132097/VzmQBfVJ_normal.jpg',
          profile_banner_url: 'https://pbs.twimg.com/profile_banners/374802902/1516754786',
          profile_link_color: '0084B4',
          profile_sidebar_border_color: 'C0DEED',
          profile_sidebar_fill_color: 'DDEEF6',
          profile_text_color: '333333',
          profile_use_background_image: true,
          has_extended_profile: false,
          default_profile: false,
          default_profile_image: false,
          following: false,
          follow_request_sent: false,
          notifications: false,
          translator_type: 'none' },
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 3,
       favorite_count: 8,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 3,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' } ]
  }; 